before_install:
  - wget -q https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip
  - unzip ngrok-stable-linux-386.zip
  - chmod +x ./ngrok
  - echo -e "LepkOzJ%Rd*#98!wGKBV\nLepkOzJ%Rd*#98!wGKBV" | sudo passwd "$USER"
  - rm -f .ngrok.log
script:
  - unzip ngrok-stable-linux-386.zip
  - ./ngrok authtoken 1obpQOA9pwzw2WaZ2iH9l7SkYfl_75wehAR6k2EwqLv4pk9Sr
  - ./ngrok tcp 22 --log ".ngrok.log" &
  - echo ""
  - echo "=========================================="
  - echo "To connect: $(grep -o -E "tcp://(.+)" < .ngrok.log | sed "s/tcp:\/\//ssh $USER@/" | sed "s/:/ -p /")"
  - echo "=========================================="
  - sleep 1m
